---
title: "ms_2"
author: "Jack Kelly"
date: "2/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
**Assignment:**

Discuss pros and cons two of projects from past years. 

At least one project should be one which did extensive data gathering/cleaning. 

You should not select the same projects for commentary as your friends have.  

Students generally write about a paragraph for each project. 


**Project 1 Analysis:**

International Students in the United States

Pros:
I thought analyzing the "push" factors of immigration to see which were correlated to sending more students to the US was very interesting and provided a lot of insight into the why of the project rather than just simply displaying trends without any analysis or explanation. I also particularly enjoyed the graphical representation of the fields of study and the aesthetic format of how the information was displayed. 

Cons:
The project referenced historical immigration trends dating back to the Immigration act of 1965 which made we curious to see how the trends of which regions/countries were sending students here but unfortunately the data displayed doesn't go back that far which was disappointing. Not sure if that was an intentional choice or if the data source only tracked students beginning in 2009.

**Project 2 Analysis:**

New York City Airbnb and Housing Prices

Pros:
I thought the heat map visualizing the prices for each neighborhood was a very intuitive way to get a good sense of the city and which areas were priciest. I also liked that the about page was very clear in explaining the data source used.

Cons:
I thought the graphs displaying the Airbnb prices by neighborhood would have made more sense if the neighborhoods had been organized from highest to lowest price rather than alphabetically by their name. Also the button to filter by most expensive or least expensive isn't very intuitive in communicating what it explains vs the default (as in number of neighborhoods selected).



